# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8e29178c75c42c0bf2da85c678a99863d8fedfd66e80a119ef7e15f9f6fd5573edeac2c89a9a28e2588a2e09b10effbbea330e975319691c1815d83302b9041

test:
  secret_key_base: 6e16cf3adf9bc6c879d374beb42cce4306709419c82d7347c0daa7f7497ed962d3eb3baf27628848c0507a591d385f2f99239a4d5c714be6ff8315def333ae19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
